layout: {zmk_keyboard: woagboard}
layers:
  base:
    - B
    - F
    - L
    - K
    - Q
    - P
    - G
    - O
    - U
    - {t: ., s: ':'}
    - {t: N, h: '$$material:keyboard_control_key$$'}
    - {t: S, h: '$$material:shift$$'}
    - {t: H, h: '$$material:keyboard_option_key$$'}
    - {t: T, h: '$$mdi:microsoft-windows$$'}
    - M
    - Y
    - {t: C, h: '$$mdi:microsoft-windows$$'}
    - {t: A, h: '$$material:keyboard_option_key$$'}
    - {t: E, h: '$$material:shift$$'}
    - {t: I, h: '$$material:keyboard_control_key$$'}
    - X
    - V
    - J
    - D
    - Z
    - {t: '''', s: '"'}
    - W
    - {t: /, s: '?'}
    - {t: ;, s: ':'}
    - {t: ',', s: ;}
    - $$mdi:microsoft-windows$$
    - {t: R, h: nav}
    - {t: '$$material:keyboard_return$$', h: fn}
    - {t: num, h: num, s: '$$mdi:alpha-w-box$$'}
    - {t: '$$material:space_bar$$', h: nav, s: '$$material:more_horiz$$'}
    - {t: '$$mdi:refresh$$', h: '$$material:shift$$', s: '$$mdi:alpha-w-box$$'}
  nav:
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - $$material:keyboard_tab_rtl$$
    - $$material:swap_horiz$$
    - {t: ▽, type: trans}
    - $$material:keyboard_double_arrow_up$$
    - {t: '$$material:backspace$$', h: 'Ctl+$$material:backspace$$'}
    - {t: '$$material:keyboard_arrow_up$$', h: Ctl+HOME}
    - {t: '$$mdi:backspace-reverse-outline$$', h: 'Ctl+$$mdi:backspace-reverse-outline$$'}
    - {t: ▽, type: trans}
    - {t: '$$mdi:microsoft-windows$$', h: sticky}
    - {t: '$$material:keyboard_option_key$$', h: sticky}
    - {t: '$$material:shift$$', h: sticky}
    - {t: '$$material:keyboard_control_key$$', h: sticky}
    - {t: ▽, type: trans}
    - {t: '$$material:keyboard_arrow_left$$', h: HOME}
    - {t: '$$material:keyboard_arrow_down$$', h: Ctl+END}
    - {t: '$$material:keyboard_arrow_up$$', h: Ctl+HOME}
    - {t: '$$material:keyboard_arrow_right$$', h: END}
    - {t: '$$material:keyboard_return$$', type: enter}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - $$material:keyboard_double_arrow_down$$
    - INS
    - $$material:keyboard_tab$$
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - CANCEL
  fn:
    - F12
    - F7
    - F8
    - F9
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - $$material:skip_previous$$
    - $$material:volume_up$$
    - $$material:skip_next$$
    - $$material:bedtime$$
    - {t: F11, h: '$$mdi:microsoft-windows$$'}
    - {t: F4, h: '$$material:keyboard_option_key$$'}
    - {t: F5, h: '$$material:shift$$'}
    - {t: F6, h: '$$material:keyboard_control_key$$'}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: 'Gui+Ctl+$$material:keyboard_arrow_left$$', h: '$$material:keyboard_control_key$$'}
    - {t: '$$material:volume_down$$', h: '$$material:shift$$'}
    - {t: 'Gui+Ctl+$$material:keyboard_arrow_right$$', h: '$$material:keyboard_option_key$$'}
    - {t: ▽, type: trans}
    - F10
    - F1
    - F2
    - F3
    - {t: ▽, type: trans}
    - Gui+Ctl+Sft+A
    - Gui+Ctl+Sft+Q
    - Alt+`
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
    - {t: ▽, type: trans}
    - $$material:play_pause$$
    - $$material:volume_off$$
  num:
    - {t: ▽, type: trans}
    - '7'
    - '8'
    - '9'
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: '0', h: '$$mdi:microsoft-windows$$'}
    - {t: '4', h: '$$material:keyboard_option_key$$'}
    - {t: '5', h: '$$material:shift$$'}
    - {t: '6', h: '$$material:keyboard_control_key$$'}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - '1'
    - '2'
    - '3'
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  sys:
    - {h: '1', s: '$$mdi:bluetooth-connect$$'}
    - {h: '2', s: '$$mdi:bluetooth-connect$$'}
    - {h: '3', s: '$$mdi:bluetooth-connect$$'}
    - {h: '4', s: '$$mdi:bluetooth-connect$$'}
    - $$mdi:bluetooth-off$$
    - $$mdi:lock$$
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: '$$mdi:unicode$$', h: '$$mdi:linux$$'}
    - {t: '$$mdi:unicode$$', h: '$$mdi:microsoft-windows$$'}
    - {t: '$$mdi:unicode$$', h: '$$mdi:apple$$'}
    - $$mdi:lock$$
    - $$mdi:progress-download$$
    - $$mdi:progress-download$$
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - $$mdi:power-off$$
    - {t: '$$mdi:backup-restore$$', type: bootloader}
    - {t: '$$mdi:backup-restore$$', type: bootloader}
    - $$mdi:power-off$$
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
    - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  Combos: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
combos:
  - p: [1, 2]
    k: $$mdi:keyboard-esc$$
    l: [Combos]
  - p: [2, 3]
    k: {t: '$$material:keyboard_return$$', type: enter}
    l: [Combos]
  - p: [11, 12]
    k: $$material:swap_horiz$$
    l: [Combos]
  - p: [12, 13]
    k: {t: '$$material:arrow_drop_up$$', h: 'Sft+$$material:keyboard_control_key$$'}
    l: [Combos]
  - p: [11, 12, 13]
    k: $$material:arrow_drop_up$$
    l: [Combos]
  - p: [21, 23]
    k: Ctl+X
    l: [Combos]
  - p: [21, 22]
    k: Ctl+INS
    l: [Combos]
  - p: [22, 23]
    k: Sft+INS
    l: [Combos]
  - p: [6, 7]
    k: {t: '$$material:backspace$$', type: backspace}
    l: [Combos]
  - p: [7, 8]
    k: $$mdi:backspace-reverse-outline$$
    l: [Combos]
  - p: [16, 17]
    k: {t: (, h: 'Sft+$$material:keyboard_control_key$$', s: <}
    l: [Combos]
  - p: [17, 18]
    k: {t: ), s: '>'}
    l: [Combos]
  - p: [16, 17]
    k: <
    l: [Combos]
  - p: [17, 18]
    k: '>'
    l: [Combos]
  - p: [26, 27]
    k: {t: '[', s: '{'}
    l: [Combos]
  - p: [27, 28]
    k: {t: ']', s: '}'}
    l: [Combos]
  - p: [26, 27]
    k: '{'
    l: [Combos]
  - p: [27, 28]
    k: '}'
    l: [Combos]
  - p: [1, 11]
    k: '@'
    l: [Combos]
  - p: [2, 12]
    k: '#'
    l: [Combos]
  - p: [3, 13]
    k: $
    l: [Combos]
  - p: [4, 14]
    k: '%'
    l: [Combos]
  - p: [11, 21]
    k: '`'
    l: [Combos]
  - p: [12, 22]
    k: \
    l: [Combos]
  - p: [13, 23]
    k: '='
    l: [Combos]
  - p: [14, 24]
    k: '~'
    l: [Combos]
  - p: [5, 15]
    k: ^
    l: [Combos]
  - p: [6, 16]
    k: +
    l: [Combos]
  - p: [7, 17]
    k: '*'
    l: [Combos]
  - p: [8, 18]
    k: '&'
    l: [Combos]
  - p: [9, 19]
    k: '!'
    l: [Combos]
  - p: [15, 25]
    k: _
    l: [Combos]
  - p: [16, 26]
    k: '-'
    l: [Combos]
  - p: [17, 27]
    k: {t: /, s: '?'}
    l: [Combos]
  - p: [18, 28]
    k: '|'
    l: [Combos]
  - p: [19, 29]
    k: '?'
    l: [Combos]
